openapi: 3.1.0

info:
  title: Access Gate API
  version: 1.0.0
  description: API kiểm soát ra vào

  contact:
    name: Team Access
    email: access@example.com

servers:
  - url: http://localhost:4010

paths:

  /access/check:
    post:
      tags:
        - Access

      operationId: checkAccess

      summary: Kiểm tra quyền truy cập

      description: API dùng để kiểm tra quyền truy cập người dùng.

      requestBody:
        required: true

        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessRequest'

      responses:

        '200':
          description: Thành công

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessResponse'

        '404':
          description: Không tìm thấy

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

  /access/logs:
    get:
      tags:
        - Access

      operationId: getAccessLogs

      summary: Lấy lịch sử truy cập

      description: API lấy danh sách lịch sử truy cập.

      responses:

        '200':
          description: Thành công

  /access/open-gate:
    post:
      tags:
        - Access

      operationId: openGate

      summary: Mở cổng

      description: API mở cổng khi người dùng hợp lệ.

      responses:

        '200':
          description: Thành công

  /users/{id}:
    get:
      tags:
        - Users

      operationId: getUserById

      summary: Lấy thông tin người dùng

      description: API lấy thông tin người dùng theo ID.

      parameters:
        - name: id
          in: path
          required: true

          schema:
            type: integer

      responses:

        '200':
          description: Thành công

components:

  schemas:

    AccessRequest:
      type: object

      properties:
        cardId:
          type: string

    AccessResponse:
      type: object

      properties:
        allowed:
          type: boolean

        username:
          type: string

        middleName:
          type:
            - string
            - "null"

    ProblemDetails:
      type: object

      properties:
        title:
          type: string

        status:
          type: integer

        detail:
          type: string

    User:
      oneOf:
        - $ref: '#/components/schemas/Student'
        - $ref: '#/components/schemas/Teacher'

      discriminator:
        propertyName: role

    Student:
      type: object

      properties:
        role:
          type: string

        studentCode:
          type: string

    Teacher:
      type: object

      properties:
        role:
          type: string

        department:
          type: string